name: azureml-deployment
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - azureml-defaults==1.43.0
      - tensorflow
      - numpy
      - Pillow
      - applicationinsights
      
